default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:820697131495:android:c5122cbb994fae6a7c3542",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type:"APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "ahmeddog185@gmail.com",
      release_notes: "First Fastlane Firebase App Distribution"
  )
  end
end
